POST /upload/single HTTP/1.1
Host: test.com:9527
Content-Type: multipart/form-data; boundary=abc

--abc
Content-Disposition: form-data; name="avatar";filename="small.jpg"
Content-Type: image/jpeg

< ./small.jpg
--abc--